title: Jessica Johnson # your name (or website title) here
logo: "/images/15809287.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Passionate data professional w/ a strong background providing enterprise business intelligence, data warehousing & analytic solutions across various industries.
  <br><br>
  <a href="https://www.jessicajohnson.net">View My Professional Page</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/johnsonjm/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
